---

- block:
    - name: define (server) | Define nginx shares global configs
      set_fact:
        _nginx_conf: >-
          {{ hostvars[item_host]._nginx_conf | default([])
              + [ share | combine(
                      { 'host'        : item_host
                      , 'name'        : item_name
                      , 'server_name' : share.server_name | default([])
                      , 'root'        : share.root | default(nginx_root + '/' + item_name)
                      , 'access_log'  : item_access_log
                      , 'error_log'   : item_error_log
                      , 'cert'        : item_cert
                      , 'privkey'     : share.privkey | default(nginx_privkey)
                      , 'conf_include_d': item_dest + '.d'
                      , 'tmpl'        : 'share_vhost.conf'
                      , 'dest'        : item_dest
                      , 'link_to'     : item_link_to
                      }
                    )
                ]
          }}
      vars:
        item_host: >-
          {{ item.server }}
        item_name: >-
          {{ item.share }}
        share: >-
          {{ hostvars[item_host].nginx_shares[item_name] }}
        item_access_log: >-
          {{ share.access_log | default(
                hostvars[item_host].nginx_log_dir + '/' + item_name + '-access.log'
                  if hostvars[item_host].nginx_log_dir is defined
                  else ''
              )
          }}
        item_error_log: >-
          {{ share.error_log | default(
                hostvars[item_host].nginx_log_dir + '/' + item_name + '-error.log'
                  if hostvars[item_host].nginx_log_dir is defined
                  else ''
              )
          }}
        item_cert: >-
          {{ share.cert | default(hostvars[item_host].nginx_cert) }}
        item_privkey: >-
          {{ share.privkey | default(hostvars[item_host].nginx_privkey) }}
        item_dest: >-
          {{ hostvars[item_host].nginx_conf_dir | default('/etc/nginx')
              + '/sites-available/' + item_name
          }}
        item_link_to: >-
          {{ hostvars[item_host].nginx_conf_dir | default('/etc/nginx')
              + '/sites-enabled/' + item_name
          }}
      loop: "{{ nginx_host_shares }}"
      delegate_facts: true
      delegate_to: "{{ item.server }}"

    - name: define | Define nginx shares host config
      set_fact:
        _nginx_host_conf: >-
          {{  _nginx_host_conf
                + [ item | combine(
                      { 'name'  : item_name
                      , 'tmpl'  : 'share.conf'
                      , 'dest'  :   item_conf_include_d + '/' + item_name + '.conf'
                      , 'htpasswd': item_conf_include_d + '/' + item_name + '.htpasswd'
                      , 'root'  : item_root
                      , 'pw' : lookup('file',
                                    lookup('first_found',
                                      [ 'htpasswords/' + inventory_hostname + '/' + item_name
                                      , 'htpasswords/' + inventory_hostname + '/default'
                                      , 'htpasswords/default'
                                      ])
                                    )
                      }
                    )
                  ]
          }}
      vars:
        item_vhost_conf: >-
          {{ hostvars[item.server]._nginx_conf
              | selectattr('name', 'equalto', item.share)
              | first
          }}
        item_name: >-
          {{ inventory_hostname }}
        item_conf_include_d: >-
          {{ item_vhost_conf.conf_include_d }}
        item_root: >-
          {{ item_vhost_conf.root + '/' + item_name }}
      loop: "{{ nginx_host_shares }}"

    - name: define | Show nginx global configs
      debug:
        var: hostvars[item.server]._nginx_conf
      loop: "{{ nginx_host_shares }}"

    - name: define | Show nginx host config
      debug:
        var: _nginx_host_conf

    - name: define | Gather all nginx global configs into single list
      set_fact:
        _nginx_conf_all: >-
          {{ _nginx_conf_all + hostvars[item]._nginx_conf }}
      loop: "{{ _nginx_servers }}"

    - name: define | Show all nginx global configs
      debug:
        var: _nginx_conf_all

