---

- block:
    - name: define | Find all nginx servers
      set_fact:
        _nginx_servers: >-
          {{ (nginx_host_shares + nginx_host_rproxy)
                | map(attribute='server')
                | unique
                | list
          }}

    - name: Gather facts about nginx servers
      setup:
      loop: "{{ _nginx_servers }}"
      delegate_to: "{{ item }}"
      delegate_facts: true

  tags:
    - always
    - nginx_define
    - nginx_shares
    - nginx_rproxy

- name: Define variables
  import_tasks: define.yml
  tags:
    - always
    - nginx_define
    - nginx_shares
    - nginx_rproxy

- name: Configure nginx
  import_tasks: nginx.yml

- name: Configure nginx shares
  import_tasks: share.yml
  tags:
    - nginx_shares

- name: Configure nginx rproxy
  import_tasks: rproxy.yml
  tags:
    - nginx_rproxy

